=== ZhangZhHua/KM2A_Monopole_Search/UpperLimit/1e10/models_UL/HistFactorySchema.dtd
<!ELEMENT Combination (Input+, Measurement+)>
<!ATTLIST Combination OutputFilePrefix CDATA #REQUIRED>
<!ELEMENT Input (#PCDATA)>
<!ELEMENT Measurement (POI, ParamSetting?, ConstraintTerm*)>
<!ATTLIST Measurement Name CDATA #REQUIRED>
<!ATTLIST Measurement Lumi CDATA #REQUIRED>
<!ATTLIST Measurement LumiRelErr CDATA #REQUIRED>
<!ATTLIST Measurement ExportOnly (True|False) "False">
<!ELEMENT POI (#PCDATA)>
<!ELEMENT ParamSetting (#PCDATA)>
<!ATTLIST ParamSetting Const (True|False) "False">
<!ELEMENT ConstraintTerm (#PCDATA)>
<!ATTLIST ConstraintTerm Type CDATA #REQUIRED>
<!ATTLIST ConstraintTerm RelativeUncertainty CDATA #REQUIRED>

<!ELEMENT Channel (Data, StatErrorConfig?, Sample*)>
<!ATTLIST Channel Name CDATA #REQUIRED>
<!ATTLIST Channel InputFile CDATA #IMPLIED>
<!ELEMENT Data EMPTY>
<!ATTLIST Data HistoName CDATA #REQUIRED>
<!ATTLIST Data InputFile CDATA #IMPLIED>
<!ATTLIST Data HistoPath CDATA #IMPLIED>
<!ELEMENT StatErrorConfig EMPTY>
<!ATTLIST StatErrorConfig RelErrorThreshold CDATA #REQUIRED>
<!ATTLIST StatErrorConfig ConstraintType (Gaussian|Poisson) "Poisson">
<!ELEMENT Sample (StatError?, NormFactor?, HistoSys*, OverallSys*, ShapeSys*)>
<!ATTLIST Sample Name CDATA #REQUIRED>
<!ATTLIST Sample HistoName CDATA #REQUIRED>
<!ATTLIST Sample InputFile CDATA #IMPLIED>
<!ATTLIST Sample HistoPath CDATA #IMPLIED>
<!ATTLIST Sample NormalizeByTheory (True|False) "True">
<!ELEMENT StatError EMPTY>
<!ATTLIST StatError Activate (True|False) "False">
<!ATTLIST StatError InputFile CDATA #IMPLIED>
<!ATTLIST StatError HistoName CDATA #IMPLIED>
<!ATTLIST StatError HistoPath CDATA #IMPLIED>
<!ELEMENT NormFactor EMPTY>
<!ATTLIST NormFactor Name CDATA #REQUIRED>
<!ATTLIST NormFactor Val CDATA #REQUIRED>
<!ATTLIST NormFactor Low CDATA #REQUIRED>
<!ATTLIST NormFactor High CDATA #REQUIRED>
<!ATTLIST NormFactor Const (True|False) "False">
<!ELEMENT HistoSys EMPTY>
<!ATTLIST HistoSys Name CDATA #REQUIRED>
<!ATTLIST HistoSys InputFileLow CDATA #IMPLIED>
<!ATTLIST HistoSys HistoNameLow CDATA #REQUIRED>
<!ATTLIST HistoSys HistoPathLow CDATA #IMPLIED>
<!ATTLIST HistoSys InputFileHigh CDATA #IMPLIED>
<!ATTLIST HistoSys HistoNameHigh CDATA #REQUIRED>
<!ATTLIST HistoSys HistoPathHigh CDATA #IMPLIED>
<!ELEMENT OverallSys EMPTY>
<!ATTLIST OverallSys Name CDATA #REQUIRED>
<!ATTLIST OverallSys Low CDATA #REQUIRED>
<!ATTLIST OverallSys High CDATA #REQUIRED>
<!ELEMENT ShapeSys EMPTY>
<!ATTLIST ShapeSys Name CDATA #REQUIRED>
<!ATTLIST ShapeSys InputFile CDATA #IMPLIED>
<!ATTLIST ShapeSys HistoName CDATA #REQUIRED>
<!ATTLIST ShapeSys HistoPath CDATA #IMPLIED>
<!ATTLIST ShapeSys ConstraintType (Gaussian|Poisson) "Gaussian">

=== ZhangZhHua/KM2A_Monopole_Search/UpperLimit/1e12/upperlimit_DataDriven/LHAASO_Channel.xml
<!DOCTYPE Channel  SYSTEM 'HistFactorySchema.dtd'>

<Channel Name="LHAASO_Monopole_Channel" InputFile="./inputs_for_roostats.root">

  <Data HistoName="h_data" />
  <StatErrorConfig RelErrorThreshold="0.001" ConstraintType="Poisson" />

  <Sample Name="Background" HistoName="h_bkg_nom" NormalizeByTheory="True">
    <StatError Activate="True" />
    <NormFactor Name="mu_bkg" Val="1.0" Low="0.0" High="5.0" />
    <HistoSys Name="BkgShapeSyst" HistoNameLow="h_bkg_ShapeDown" HistoNameHigh="h_bkg_ShapeUp" />
  </Sample>

  <Sample Name="Signal" HistoName="h_sig_nom" NormalizeByTheory="True">
    <StatError Activate="True" />
    <NormFactor Name="mu" Val="1.0" Low="0.0" High="10.0" />
    <OverallSys Name="recE_shift" Low="0.9962" High="1.0038" />
    <OverallSys Name="R_ue_shift" Low="0.9986" High="1.0014" />
    <OverallSys Name="thetaRec_resolution" Low="0.9998" High="1.0002" />
    <HistoSys Name="SigShapeSyst" HistoNameLow="h_sig_ShapeDown" HistoNameHigh="h_sig_ShapeUp" />
  </Sample>

</Channel>

=== ZhangZhHua/KM2A_Monopole_Search/UpperLimit/1e10/models_UL/single_channel.xml
<!DOCTYPE Channel SYSTEM "HistFactorySchema.dtd">

<Channel Name="single_channel" InputFile="inputs_for_roostats.root">
  
  <Data HistoName="h_data" />

  <StatErrorConfig RelErrorThreshold="0.001" ConstraintType="Poisson" />

  <Sample Name="background" HistoName="h_bkg_nom" NormalizeByTheory="True">
    <StatError Activate="True" />
    <NormFactor Name="mu_bkg" Val="1.0" Low="0.0" High="5.0" />
    <OverallSys Name="models_Ruecut_yield_sys" Low="0.9860" High="1.0084"/>
    <OverallSys Name="spectrum_yield_sys" Low="0.8954" High="1.1046"/>
    <HistoSys Name="energy_cali_sys" HistoNameLow="h_bkg_recE_down" HistoNameHigh="h_bkg_recE_up"/>
    <HistoSys Name="template_stability_sys" HistoNameLow="h_bkg_rue_down" HistoNameHigh="h_bkg_rue_up"/>
    <HistoSys Name="model_shape_sys" HistoNameLow="h_bkg_model_lo" HistoNameHigh="h_bkg_model_hi"/>
  </Sample>

  <Sample Name="signal" HistoName="h_sig_nom" NormalizeByTheory="True">
    <NormFactor Name="mu" Val="1.0" Low="0.0" High="20.0" />
    <HistoSys Name="energy_cali_sys" HistoNameLow="h_sig_recE_down" HistoNameHigh="h_sig_recE_up"/>
  </Sample>

</Channel>

=== ZhangZhHua/KM2A_Monopole_Search/UpperLimit/1e11/upperlimit_DataDriven/LHAASO_Channel.xml
<!DOCTYPE Channel  SYSTEM 'HistFactorySchema.dtd'>

<Channel Name="LHAASO_Monopole_Channel" InputFile="./inputs_for_roostats.root">

  <Data HistoName="h_data" />
  <StatErrorConfig RelErrorThreshold="0.001" ConstraintType="Poisson" />

  <Sample Name="Background" HistoName="h_bkg_nom" NormalizeByTheory="True">
    <StatError Activate="True" />
    <NormFactor Name="mu_bkg" Val="1.0" Low="0.0" High="5.0" />
    <OverallSys Name="BkgNormUnc" Low="0.88" High="1.12" /> 
    <HistoSys Name="BkgShapeSyst" HistoNameLow="h_bkg_ShapeDown" HistoNameHigh="h_bkg_ShapeUp" />
  </Sample>

  <Sample Name="Signal" HistoName="h_sig_nom" NormalizeByTheory="True">
    <StatError Activate="True" />
    <NormFactor Name="mu" Val="1.0" Low="0.0" High="10.0" />
  </Sample>

</Channel>
